spring.application.name=quick-commerce-delivery-system
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Database Configuration (Development)
spring.datasource.url=jdbc:h2:mem:quick_commerce
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true

server.port=8080
server.servlet.context-path=/

# JWT Configuration
jwt.secret=your-secret-key-make-it-long-and-random-for-production
jwt.expiration=86400000
